Repository myalley-project/myalley-fe, pull requests merged in 2022-12, with the labels that each got.

#2 Docs: global-styles, theme 관련 파일 추가
  src/index.tsx
  src/styles/global-styles.tsx
  src/styles/styled.d.tsx
  src/styles/theme.tsx
Labels: documentation

#5 Setting: eslint no-use-before-define 설정 off
  .eslintrc.json
Labels: documentation

#13 Remove: .eslintcache 파일 제거
  .eslintcache
  package-lock.json
  yarn.lock
Labels: bug

#12 Design: global-style에 div, input, button border-radius 설정추가
  src/styles/global-styles.tsx
Labels: help wanted

#15 Setting: 초기세팅 추가
  .barbelrc
  .eslintrc.json
  .gitignore
  .gitmessage.txt
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/component/Component.tsx
  src/components/Footer.tsx
  src/components/Nav.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/exhibition/Exhibition.tsx
  src/pages/exhibitionList/ExhibitionList.tsx
  src/pages/login/Login.tsx
  src/pages/main/Main.tsx
  src/pages/signUp/SignUp.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/global-styles.tsx
  src/styles/styled.d.tsx
  src/styles/theme.tsx
  yarn.lock
Labels: documentation, merge main

#27 Setting: package.json eslint 대상 경로 변경
  package.json
Labels: bug

#19 Design: 회원용/관리자용 회원가입 UI 완성
  src/App.tsx
  src/assets/icons/arrowDown.svg
  src/components/LoginSignUp.style.tsx
  src/function/signUp/signUpBirth.tsx
  src/pages/signUp/SignUp.tsx
Labels: enhancement, on change
