Repository myalley-project/myalley-fe, pull requests merged in 2023-03, with the labels that each got.

#443 Fix: 전시회상세페이지 북마크 실패해도 아이콘 변경되는 오류 수정
  src/components/atom/BookMark.tsx
  src/components/exhibition/MainCard.tsx
Labels: bug

#449 Fix: 전시회상세페이지 북마크 실패해도 아이콘 변경되는 오류 수정
  src/components/atom/BookMark.tsx
  src/components/exhibition/MainCard.tsx
Labels: merge main

#448 Fix: 한 줄 리뷰 서치바 필터영역 css 수정
  src/components/onelineReview/container/OneLineReadContainer.tsx
  src/components/onelineReview/presentation/OnelineCard.tsx
  src/components/reviewCommon/ReviewSearchBar.tsx
Labels: fix, design

#450 Fix: 전시회 목록 조회 요청 실패 시 메인페이지로 리다이렉트
  src/pages/ExhibitionList.tsx
Labels: fix

#454 Fix: 전시회 목록 조회 요청 실패 시 메인페이지로 리다이렉트
  src/pages/ExhibitionList.tsx
Labels: merge main

#455 Fix: 전시리뷰 작성페이지 날짜 두번 클릭해야 선택되는 오류 수정
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
Labels: bug

#456 Fix: 전시리뷰 작성페이지 날짜 두번 클릭해야 선택되는 오류 수정
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
Labels: merge main

#451 Feat: 전시회 모달 스크롤화
  src/components/ExhibitionChoice.tsx
  src/components/blogreview/ExhibitionSelect.tsx
  src/components/exhbChoiceModal/ExhbCardListModal.tsx
Labels: enhancement, design

#458 Fix: 블로그리뷰 작성페이지 selectedDate 초기값 포맷형태 yyyy-MM-dd로 수정
  src/pages/BlogReviewWrite.tsx
Labels: bug

#459 Fix: 블로그리뷰 작성페이지 selectedDate 초기값 포맷형태 yyyy-MM-dd로 수정
  src/pages/BlogReviewWrite.tsx
Labels: merge main

#460 Fix: 블로그 리뷰 수정글 기존 글 정보 표시되도록 수정
  src/components/Calendar.tsx
  src/components/Editor.tsx
  src/components/blogreview/ReviewTitle.tsx
  src/components/blogreview/presentation/BlogReviewPresentation.tsx
  src/pages/BlogReview.tsx
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
Labels: bug, enhancement

#462 Feat: 이미지 우클릭 방지 기능 추가
  public/index.html
Labels: enhancement

#464 Feat: 이미지 우클릭 방지 기능 추가
  public/index.html
Labels: merge main

#466 Fix: 리뷰 상세페이지 state 갱신 지연 수정
  src/pages/BlogReview.tsx
Labels: bug

#469 Docs/readme
  README.md
Labels: documentation

#471 Fix: 비 로그인시 블로그 리뷰 상세표시와 css 정렬수정
  src/apis/blogReviewApis.tsx
  src/components/blogReviewList/ReviewCard.tsx
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/onelineReview/presentation/MypageOnelineCard.tsx
Labels: bug

#473 Fix: 전시글목록 api 수정사항 반영(전시회 제목 검색 title 파라미터 추가, sort/type파라미터 기본값 ""으로 수정"
  src/apis/exhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: fix

#474 Fix: 전시글목록 api 수정사항 반영(전시회 제목 검색 title 파라미터 추가, sort/type파라미터 기본값 ""으로 수정)
  src/apis/exhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: merge main

#475 HOTFIX: 전시회 목록, 메이트글 목록 조회 api 응답형식 변경(totalPage 부분) 미반영으로 인한 오류 수정
  src/apis/exhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/pages/ExhibitionList.tsx
  src/pages/MateList.tsx
  src/types/mateList.d.ts
Labels: bug

#476 HOTFIX: 전시글 목록조회, 메이트글 목록조회 api 응답형식 미반영으로 인한 에러 수정
  src/apis/exhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/pages/ExhibitionList.tsx
  src/pages/MateList.tsx
  src/types/mateList.d.ts
Labels: bug

#478 ReadMe: 백엔드 기술스택 이미지 변경
  README.md
Labels: readme

#477 Fix: 메이트글 목록조회api 수정사항 반영
  src/apis/mate.tsx
Labels: fix

#479 Fix: 메이트글 목록조회api 수정사항(title추가, status '전체'일 시 공백으로 요청) 반영
  src/apis/mate.tsx
Labels: merge main

#480 Feat: 블로그 리뷰 검색기능 작성
  src/hooks/useDebounce.tsx
  src/pages/BlogReviewList.tsx
Labels: enhancement

#486 Fix: page info api 수정
  src/apis/member.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/WrittenMate.tsx
Labels: fix

#487 Fix: page info api 수정
  src/apis/member.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/WrittenMate.tsx
Labels: merge main

#489 Feat: 전시회목록 전시제목으로 검색하는 기능 추가
  src/apis/exhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: enhancement

#491 Fix: 전시회목록 페이지 상태버튼 클릭 시 검색어 초기화
  src/components/exhibitionList/Filters.tsx
Labels: fix
