Repository myalley-project/myalley-fe, pull requests merged in 2023-01, with the labels that each got.

#30 Design: 메인 테마 컬러 추가
  src/styles/theme.tsx
Labels: documentation

#34 Setting: utils, hooks폴더 추가, function폴더 삭제, pages폴더 내 하위폴더 삭제
  src/App.tsx
  src/assets/images/.gitkeep
  src/function/signUp/signUpBirth.tsx
  src/hooks/.gitkeep
  src/pages/Exhibition.tsx
  src/pages/ExhibitionList.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/SignUp.tsx
  src/utils/.gitkeep
Labels: documentation

#32 Feat: Modal 공용 컴포넌트 작성 #24
  public/index.html
  src/Modal.tsx
Labels: enhancement

#35 Setting: utils, hooks폴더 추가, function폴더 삭제, pages폴더 내 하위폴더 삭제
  public/index.html
  src/App.tsx
  src/Modal.tsx
  src/assets/images/.gitkeep
  src/hooks/.gitkeep
  src/pages/Exhibition.tsx
  src/pages/ExhibitionList.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/SignUp.tsx
  src/utils/.gitkeep
Labels: merge main

#31 Feat: 로그인 와이어프레임 UI 완성 #3
  src/assets/icons/checkboxOff.svg
  src/assets/icons/checkboxOn.svg
  src/components/LoginSignUp.style.tsx
  src/pages/Login.tsx
Labels: enhancement, on change

#37 Feat: 로그인 와이어프레임 UI 완성 #3 (#31)
  src/assets/icons/checkboxOff.svg
  src/assets/icons/checkboxOn.svg
  src/components/LoginSignUp.style.tsx
  src/pages/Login.tsx
Labels: merge main

#39 Feat: 햄버거메뉴 구현
  src/assets/icons/UserMenu.svg
  src/assets/icons/menu.svg
  src/assets/icons/userMenuHover.svg
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/exhibition/mainCard.tsx
  src/components/exhibition/toggleSwitch.tsx
  src/pages/Exhibition.tsx
Labels: enhancement

#47 !HOTFIX: 파일명 대소문자 오류 재수정
  src/assets/icons/UserMenu.svg
  src/components/exhibition/MainCard.tsx
  src/components/exhibition/contentCard.tsx
Labels: bug

#48 !HOTFIX: 파일명 대소문자 오류 재수정 (#47)
  src/assets/icons/UserMenu.svg
  src/components/exhibition/MainCard.tsx
  src/components/exhibition/contentCard.tsx
Labels: bug, merge main

#45 Feat: api instance 생성, gitingnore에 .env파일 추가
  .gitignore
  src/utils/.gitkeep
  src/utils/apiInstance.tsx
Labels: enhancement

#52 !HOTFIX: axios header 타입 에러 수정
  src/utils/apiInstance.tsx
Labels: bug, merge main

#53 !HOTFIX: axios header 타입 에러 수정 (to dev)
  src/utils/apiInstance.tsx
Labels: bug

#54 Setting: 자간 설정 추가, 파일명 수정
  src/index.tsx
  src/styles/globalStyles.tsx
Labels: enhancement

#56 Setting: 자간 설정 추가, 파일명 수정
  src/index.tsx
  src/styles/globalStyles.tsx
  src/utils/apiInstance.tsx
Labels: merge main

#64 Feat: 로그아웃 커스텀 훅 완성 #62
  public/data/logOut.json
  src/hooks/useLogOut.tsx
Labels: enhancement

#67 Setting: jsx-a11y/no-static-element-interactions 무효화
  .eslintrc.json
Labels: documentation

#69 Docs: .eslintrc 추가 수정
  .eslintrc.json
Labels: documentation

#59 Design: 메인페이지 카드 컴포넌트 추가
  src/assets/icons/arrowButton.svg
  src/components/MainArticle.tsx
  src/pages/Main.tsx
Labels: enhancement

#68 Feat: 캘린더 컴포넌트 ui 작성
  .eslintrc.json
  package.json
  src/assets/icons/arrowNext.svg
  src/assets/icons/arrowPrev.svg
  src/components/Calendar.tsx
  yarn.lock
Labels: enhancement

#70 Feat: 에디터 작성
  .eslintrc.json
  src/Modal.tsx
  src/assets/icons/plusButton.svg
  src/components/Editor.tsx
  src/components/Selector.tsx
  src/components/SubTitle.tsx
  src/components/blogreview/ConvenienceSelect.tsx
  src/components/blogreview/ExhibitionSelect.tsx
  src/components/blogreview/ReviewTitle.tsx
  src/components/blogreview/TimeSelect.tsx
  src/hooks/useInput.tsx
  src/utils/returnkeys.tsx
Labels: enhancement

#72 Setting: 확정된 색상 theme에 추가, 기존 main, hover, pressed, txt등 임시 네이밍 변경
  src/components/HamburgerMenu.tsx
  src/components/LoginSignUp.style.tsx
  src/components/Nav.tsx
  src/components/exhibition/MainCard.tsx
  src/components/exhibition/ToggleSwitch.tsx
  src/components/signUp/CommonOnly.tsx
  src/styles/theme.tsx
Labels: documentation

#60 Feat: 메인페이지 슬라이더 추가
  package.json
  src/assets/images/firstSlideImage.jpg
  src/assets/images/secondSlideImage.jpg
  src/assets/images/thirdSlideImage.jpg
  src/components/Carousel.tsx
  src/components/Selector.tsx
  src/pages/Main.tsx
  yarn.lock
Labels: enhancement

#80 Fix: theme 변경으로 인한 dev 오류 수정
  src/components/Calendar.tsx
  src/components/Editor.tsx
  src/components/Selector.tsx
  src/components/blogreview/ReviewTitle.tsx
  src/components/blogreview/TimeSelect.tsx
Labels: bug

#83 Fix: theme 변경으로 인한 dev 오류 수정
  src/components/Calendar.tsx
  src/components/Editor.tsx
  src/components/Selector.tsx
  src/components/blogreview/ReviewTitle.tsx
  src/components/blogreview/TimeSelect.tsx
Labels: bug, merge main

#76 Fix: 반응형 수정, 디자인 변경 사항 반영, api 통신 테스트
  src/apis/exhibition.tsx
  src/components/exhibition/ContentCard.tsx
  src/components/exhibition/MainCard.tsx
  src/components/exhibition/ToggleSwitch.tsx
  src/pages/Exhibition.tsx
Labels: enhancement

#89 Design: nav, footer 디자인 변경
  src/assets/icons/logo.svg
  src/assets/icons/profileImg.svg
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: enhancement

#96 Merge: 바뀐 nav, footer 디자인 반영
  src/assets/icons/logo.svg
  src/assets/icons/profileImg.svg
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: merge main

#88 Feat: 전시글 작성 페이지 작업, selectbox 컴포넌트 완성
  package.json
  src/App.tsx
  src/components/Selectbox.tsx
  src/lib/datePicker.d.ts
  src/pages/ExhibitionWrite.tsx
  src/styles/datePickerStyle.css
  yarn.lock
Labels: enhancement

#99 Feat: 모달 컴포넌트 완성되었습니다.
  public/index.html
  src/Modal.tsx
  src/components/ExhibitionChoice.tsx
  src/components/SimpleDialog.tsx
  src/components/atom/Button.tsx
Labels: enhancement

#101 Feat: 회원가입api 에러처리 로직 수정, 공통 에러처리 함수 isApiError 추가
  .eslintrc.json
  public/data/signUp.json
  src/apis/signUp.tsx
  src/pages/SignUp.tsx
  src/utils/isApiError.tsx
Labels: enhancement

#92 Feat: 리프레시 토큰 api 추가, 로그아웃 api 일부 변경
  public/data/expiredAccessToken.json
  public/data/login.json
  public/data/refreshToken.json
  src/apis/logOut.tsx
  src/apis/login.tsx
  src/apis/useRefreshToken.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/utils/apiInstance.tsx
  src/utils/isApiError.tsx
Labels: enhancement, on change

#109 Feat: 리프레시 토큰 api 추가, 로그아웃 api 일부 변경
  public/data/expiredAccessToken.json
  public/data/login.json
  public/data/refreshToken.json
  src/apis/logOut.tsx
  src/apis/login.tsx
  src/apis/useRefreshToken.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/utils/apiInstance.tsx
  src/utils/isApiError.tsx
Labels: on change, merge main

#105 Fix: SimpleDialog 컴포넌트 수정
  src/components/SimpleDialog.tsx
Labels: enhancement

#112 Feat: CheckLabel 컴포넌트 완성
  src/components/atom/CheckLabel.tsx
Labels: enhancement

#117 Feat: 한줄 리뷰 작성 모달 UI 완성
  src/assets/icons/starIcon.svg
  src/components/atom/SimpleInput.tsx
  src/components/onelineReview/OnelineCard.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/utils/dateSelector.tsx
  src/utils/timeSelector.tsx
Labels: enhancement

#110 Feat: 마이페이지 ui, 기능 작업, Selectbox 컴포넌트 수정
  src/App.tsx
  src/apis/mypage.tsx
  src/assets/icons/cameraCircle.svg
  src/assets/icons/profileImg.svg
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/Selectbox.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MenuButtons.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/pages/ExhibitionWrite.tsx
  src/pages/Mypage.tsx
  src/styles/labelAndInputStyles.tsx
Labels: enhancement

#123 Feat: 마이페이지 ui, 기능 작업, Selectbox 컴포넌트 수정
  src/App.tsx
  src/apis/mypage.tsx
  src/assets/icons/cameraCircle.svg
  src/assets/icons/profileImg.svg
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/Selectbox.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MenuButtons.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/pages/ExhibitionWrite.tsx
  src/pages/Mypage.tsx
  src/styles/labelAndInputStyles.tsx
Labels: merge main

#114 Fix: 가로 스크롤 생김 현상 수정
  src/components/Footer.tsx
  src/components/Nav.tsx
Labels: enhancement

#120 Feat: 메인 페이지 UI 작성
  src/components/Carousel.tsx
  src/components/MainArticle.tsx
  src/components/blogreview/TimeSelect.tsx
  src/pages/Main.tsx
Labels: enhancement

#126 Feat: 메이트 모집글 목록 컴포넌트 완성
  src/apis/mypage.tsx
  src/assets/icons/partition.svg
  src/components/mate/MateCard.tsx
  src/components/mypage/FindMate.tsx
  src/pages/Mypage.tsx
  src/types/mateList.d.ts
  src/utils/apiInstance.tsx
Labels: enhancement

#132 Fix: 회원가입 페이지 리다이렉트 기능추가, Selectbox, Button 컴포넌트사용해 재구현
  src/components/LoginSignUp.style.tsx
  src/components/atom/Selectbox.tsx
  src/components/mypage/EditProfile.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/components/signUp/CommonOnly.tsx
  src/pages/BlogReviewList.tsx
  src/pages/BlogReviewWrite.tsx
  src/pages/ExhibitionWrite.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: enhancement

#144 Feat: ROLE에 따라 보이는 메뉴 처리, 라우팅 추가
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: enhancement

#138 Design: 페이지네이션 레이아웃 깨짐 수정
  src/assets/images/.gitkeep
  src/components/Pagination.tsx
  src/hooks/.gitkeep
  src/pages/ExhibitionList.tsx
Labels: bug

#147 Design: 페이지네이션 레이아웃 깨짐 수정
  src/assets/images/.gitkeep
  src/components/Pagination.tsx
  src/hooks/.gitkeep
  src/pages/ExhibitionList.tsx
Labels: bug, merge main

#139 Fix: 로그아웃 시 로컬스토리지 정보 삭제, 로그인 시 로컬스토리지 저장되는 정보 수정, 로그아웃버튼에 로그아웃 적용 #129
  src/apis/logOut.tsx
  src/apis/member.tsx
  src/components/HamburgerMenu.tsx
  src/pages/Login.tsx
Labels: enhancement

#146 Fix: 전시회카드목록 컴포넌트화
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/ExhibitionCard.tsx
  src/pages/ExhibitionList.tsx
Labels: enhancement

#149 Fix: 전시회카드목록 컴포넌트화
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/ExhibitionCard.tsx
  src/pages/ExhibitionList.tsx
Labels: enhancement, merge main

#142 Feat: 마이페이지의 세부페이지 라우팅 추가, 회원정보api 통신 완료
  src/App.tsx
  src/apis/login.tsx
  src/apis/member.tsx
  src/apis/mypage.tsx
  src/apis/signUp.tsx
  src/components/mypage/FindMate.tsx
  src/components/mypage/MenuBtns.tsx
  src/components/mypage/MenuButtons.tsx
  src/components/mypage/MyBookmark.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/MyProfileEdit.tsx
  src/components/mypage/MyWrite.tsx
  src/components/mypage/WriteMenuBtns.tsx
  src/index.tsx
  src/pages/Mypage.tsx
  src/types/pageInfo.d.ts
Labels: enhancement

#154 Feat: 목록 없을때 보여지는 컴포넌트 완성
  src/components/NoList.tsx
  src/components/mypage/FindMate.tsx
Labels: enhancement

#156 Feat: 목록 없을때 보여지는 컴포넌트 완성
  src/components/NoList.tsx
  src/components/mypage/FindMate.tsx
Labels: enhancement

#153 Feat: 메이트글 목록 페이지 완성
  public/data/mateList.json
  src/App.tsx
  src/apis/mate.tsx
  src/components/atom/Selectbox.tsx
  src/components/mate/MateCard.tsx
  src/components/mate/MateListFilter.tsx
  src/components/mypage/FindMate.tsx
  src/pages/MateList.tsx
  src/types/mateList.d.ts
Labels: enhancement

#158 Feat: 메이트글 목록 페이지 완성
  public/data/mateList.json
  src/App.tsx
  src/apis/mate.tsx
  src/components/atom/Selectbox.tsx
  src/components/mate/MateCard.tsx
  src/components/mate/MateListFilter.tsx
  src/components/mypage/FindMate.tsx
  src/pages/MateList.tsx
  src/types/mateList.d.ts
Labels: merge main

#155 Feat: 메이트글 상세페이지 완성
  public/data/mate.json
  public/data/mateBookmark.json
  src/App.tsx
  src/apis/mate.tsx
  src/assets/icons/plusLarge.svg
  src/components/Calendar.tsx
  src/components/mate/Comment.tsx
  src/components/mate/CommentList.tsx
  src/components/mate/ExhbCard.tsx
  src/pages/Mate.tsx
  src/types/mate.d.ts
Labels: enhancement

#157 Feat: 전시글 CRUD 완성, 북마크 완성, NoList 속성 변경
  src/App.tsx
  src/apis/exhbAdmin.tsx
  src/apis/exhbBookmark.tsx
  src/apis/exhibition.tsx
  src/components/Calendar.tsx
  src/components/NoList.tsx
  src/components/Pagination.tsx
  src/components/atom/BookMark.tsx
  src/components/atom/Selectbox.tsx
  src/components/atom/labelInput.tsx
  src/components/blogreview/TimeSelect.tsx
  src/components/exhibition/ContentCard.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
  src/components/exhibition/ToggleSwitch.tsx
  src/components/mypage/FindMate.tsx
  src/components/mypage/MyProfileEdit.tsx
  src/components/mypage/MyWrite.tsx
  src/pages/Exhibition.tsx
  src/pages/ExhibitionWrite.tsx
  yarn.lock
Labels: enhancement

#163 Feat: 에디터 컴파운드 컴포넌트화 완료
  src/assets/icons/plusLarge.svg
  src/components/Editor.tsx
  src/pages/BlogReviewWrite.tsx
Labels: enhancement

#162 Feat: 마이페이지 회원정보 완성, 세부 페이지 추가
  src/apis/member.tsx
  src/components/mypage/BookMarkedPosts.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MenuBtns.tsx
  src/components/mypage/MyBookmark.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/SubMenuBtns.tsx
  src/components/mypage/WrittenMates.tsx
  src/components/mypage/WrittenPosts.tsx
  src/pages/Mypage.tsx
  src/utils/dateSelector.tsx
Labels: enhancement

#167 Feat: 마이페이지 회원정보 완성, 세부 페이지 추가
  src/apis/member.tsx
  src/components/mypage/BookMarkedPosts.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MenuBtns.tsx
  src/components/mypage/MyBookmark.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/SubMenuBtns.tsx
  src/components/mypage/WrittenMates.tsx
  src/components/mypage/WrittenPosts.tsx
  src/pages/Mypage.tsx
  src/utils/dateSelector.tsx
Labels: merge main

#169 Fix: 에디터 컴포넌트 name, value props 추가
  src/components/Editor.tsx
  src/pages/BlogReviewWrite.tsx
Labels: enhancement

#178 Fix: 에디터 컴포넌트 name, value props 추가
  src/components/Editor.tsx
  src/pages/BlogReviewWrite.tsx
Labels: enhancement, merge main

#177 Feat: 캘린더 컴포넌트 수정
  src/components/Calendar.tsx
  src/pages/BlogReviewWrite.tsx
Labels: on change

#184 Fix: 페이지 수 0일 때 display:none 적용
  src/components/Pagination.tsx
Labels: merge main

#173 Design: 회원가입 UI 수정
  src/assets/icons/alertCircle.svg
  src/components/LoginSignUp.style.tsx
  src/components/signUp/AdminOnly.tsx
  src/components/signUp/CommonOnly.tsx
  src/components/signUp/EmailAndPw.tsx
  src/pages/SignUp.tsx
  src/types/signUp.d.ts
Labels: enhancement

#171 Feat: 마이페이지의 하위 페이지들 작업 완료
  src/apis/member.tsx
  src/components/SimpleDialog.tsx
  src/components/atom/labelInput.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/BookMarkedPosts.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MenuBtns.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/SubMenuBtns.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/mypage/WrittenPosts.tsx
  src/components/mypage/WrittenSimpleReview.tsx
Labels: enhancement

#186 Fix: 로그아웃, 리프레시 토큰 인증 api 수정
  src/apis/logOut.tsx
  src/apis/useRefreshToken.tsx
  src/utils/removeLocalStorageItem.tsx
Labels: enhancement

#192 Fix: 로그아웃, 리프레시 토큰 인증 api 수정
  src/apis/logOut.tsx
  src/apis/useRefreshToken.tsx
  src/utils/removeLocalStorageItem.tsx
Labels: merge main

#189 Feat: 마이페이지 이미지 관련 로직 완성, 북마크 페이지 완성
  src/assets/icons/error.svg
  src/components/atom/labelInput.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyInfoCard.tsx
  src/pages/Mypage.tsx
Labels: enhancement

#190 Design: 전시글 작성 페이지 디자인 디테일 추가
  src/App.tsx
  src/apis/exhbAdmin.tsx
  src/components/atom/labelInput.tsx
  src/pages/ExhibitionWrite.tsx
  src/styles/datePickerStyle.css
  src/styles/theme.tsx
Labels: enhancement

#196 Design: 전시글 작성 페이지 디자인 디테일 추가
  src/App.tsx
  src/apis/exhbAdmin.tsx
  src/components/atom/labelInput.tsx
  src/pages/ExhibitionWrite.tsx
  src/styles/datePickerStyle.css
  src/styles/theme.tsx
Labels: merge main

#191 Fix: selectbox 호버시 색상 변경, outside click 기능 추가
  src/components/atom/Selectbox.tsx
Labels: enhancement

#197 Fix: selectbox 호버시 색상 변경, outside click 기능 추가
  src/components/atom/Selectbox.tsx
Labels: merge main

#195 Feat: 토큰 만료시 토큰 재발급 로직 작성, 적용 완료
  src/apis/useGetRefreshToken.tsx
  src/apis/useRefreshToken.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/mypage/WrittenSimpleReview.tsx
  src/pages/Mypage.tsx
Labels: enhancement
