Repository myalley-project/myalley-fe, pull requests merged in 2023-02, with the labels that each got.

#188 Feat: 햄버거 메뉴 프사 추가, outside click 기능 추가
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: enhancement

#201 Feat: 햄버거 메뉴 프사 추가, outside click 기능 추가
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: merge main

#200 Fix: 페이지네이션 적용 부분 수정, 메이트 모집글 링크 추가
  src/apis/exhbAdmin.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
Labels: enhancement

#202 Fix: 페이지네이션 적용 부분 수정, 메이트 모집글 링크 추가
  src/apis/exhbAdmin.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
Labels: merge main

#206 Refactor: 배포 전 점검(목데이터 말고 api로 연결, css 깨짐 수정, NoList컴포넌트 props추가)
  src/apis/getExhbList.tsx
  src/apis/mate.tsx
  src/components/NoList.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/components/main/MainArticle.tsx
  src/components/mate/MateCard.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/signUp/EmailAndPw.tsx
  src/pages/ExhibitionList.tsx
  src/pages/Login.tsx
  src/pages/MateList.tsx
  src/types/exhbList.d.ts
Labels: enhancement

#210 Refactor: 전체적인 css 깨짐 수정, 주석삭제, 목데이터 대신 api 연결, 에러 해결
  src/apis/getExhbList.tsx
  src/apis/mate.tsx
  src/components/NoList.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/components/main/MainArticle.tsx
  src/components/mate/MateCard.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/signUp/EmailAndPw.tsx
  src/pages/ExhibitionList.tsx
  src/pages/Login.tsx
  src/pages/MateList.tsx
  src/types/exhbList.d.ts
Labels: merge main

#165 Feat: 한줄 리뷰 CRUD 기능 작성
  src/Modal.tsx
  src/apis/oneLineReviewApis.tsx
  src/apis/onelineReviewapis.tsx
  src/components/ReviewSearchbar.tsx
  src/components/ReviewWrapper.tsx
  src/components/atom/Searchbar.tsx
  src/components/atom/SimpleInput.tsx
  src/components/onelineReview/OnelineCard.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/components/onelineReview/temp/OnelineTempQuery.tsx
  src/pages/Exhibition.tsx
  src/pages/Main.tsx
  src/pages/OnelineWrapper.tsx
  src/types/OnelineReview.d.ts
  src/types/oneLineReview.d.ts
Labels: enhancement

#214 Fix: 전시회 선택 모달 수정사항 반영
  src/components/ExhibitionChoice.tsx
  src/components/exhbChoiceModal/ExhbCardListModal.tsx
  src/components/exhibition/ExhibitionChoiceCard.tsx
  src/components/main/MainArticle.tsx
  src/pages/ExhibitionList.tsx
Labels: enhancement

#219 Fix: 회원정보 수정 이미지 업로드 에러 수정, 유효성 검사 수정
  src/components/mypage/EditProfile.tsx
Labels: enhancement

#223 Fix: 전시회 목록 필터적용 버튼 삭제 #216
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
  src/types/exhbList.d.ts
Labels: fix

#224 Fix: 전시회 목록 필터적용 버튼 삭제
  src/Modal.tsx
  src/apis/oneLineReviewApis.tsx
  src/components/ExhibitionChoice.tsx
  src/components/ReviewWrapper.tsx
  src/components/exhbChoiceModal/ExhbCardListModal.tsx
  src/components/exhibition/ExhibitionChoiceCard.tsx
  src/components/exhibitionList/Filters.tsx
  src/components/main/MainArticle.tsx
  src/components/mypage/EditProfile.tsx
  src/components/onelineReview/OnelineCard.tsx
  src/components/onelineReview/OnelineWrite.tsx
  src/pages/ExhibitionList.tsx
  src/pages/OnelineWrapper.tsx
  src/types/exhbList.d.ts
Labels: merge main

#198 Feat: 메이트글 작성/수정 페이지 완성
  src/App.tsx
  src/apis/mate.tsx
  src/components/Calendar.tsx
  src/components/atom/Button.tsx
  src/components/mate/MateListFilter.tsx
  src/pages/BlogReviewWrite.tsx
  src/pages/Mate.tsx
  src/pages/MateList.tsx
  src/pages/MateWrite.tsx
  src/types/mate.d.ts
Labels: enhancement

#225 Feat: 메이트글 작성/수정 페이지 완성
  src/App.tsx
  src/apis/mate.tsx
  src/components/Calendar.tsx
  src/components/atom/Button.tsx
  src/components/mate/MateListFilter.tsx
  src/pages/BlogReviewWrite.tsx
  src/pages/Mate.tsx
  src/pages/MateList.tsx
  src/pages/MateWrite.tsx
  src/types/mate.d.ts
Labels: merge main

#228 Design: Button 컴포넌트 focus, active 시 빠진 디자인 추가
  src/components/atom/Button.tsx
Labels: design

#231 Design: Button 컴포넌트 focus, active 시 빠진 디자인 추가
  src/components/atom/Button.tsx
Labels: merge main

#235 Fix: 한줄리뷰에서 전시회 아이디 입력 오류 수정
  src/components/onelineReview/container/OnelineContainer.tsx
  src/components/onelineReview/presentation/OnelineCard.tsx
  src/components/onelineReview/presentation/OnelineWrite.tsx
  src/components/reviewCommon/ReviewSearchBar.tsx
  src/components/reviewCommon/ReviewWrapper.tsx
  src/pages/Exhibition.tsx
Labels: bug

#238 Fix: 비로그인시 전시글 상세정보 안보이는 오류 해결
  src/apis/exhibition.tsx
  src/components/exhibition/MainCard.tsx
  src/pages/Exhibition.tsx
Labels: enhancement

#240 Fix: 햄버거메뉴 반응형 적용, 문의하기 구글폼 연결
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
Labels: enhancement

#242 Fix: 햄버거메뉴 반응형 적용, 문의하기 구글폼 연결
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
Labels: merge main

#232 Design: 전시회 목록페이지 max-width추가, 공통 버튼 컴포넌트로 변경
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: design

#234 Fix: 전시회 상세페이지에 들어가면 최상단으로 스크롤 올라오도록 수정
  src/App.tsx
  src/components/ScrollTop.tsx
  src/pages/Exhibition.tsx
Labels: fix

#245 Feat: ScrollTop 컴포넌트 추가
  src/App.tsx
  src/components/ScrollTop.tsx
  src/pages/Exhibition.tsx
Labels: merge main

#247 Fix: 블로그리뷰 작성 이미지 업로드 메서드 수정
  src/apis/blogReviewApis.tsx
  src/apis/oneLineReviewApis.tsx
  src/components/ExhibitionChoice.tsx
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/blogreview/container/BlogReviewList.tsx
  src/components/blogreview/presentation/BlogReviewCard.tsx
  src/pages/BlogReview.tsx
  src/pages/BlogReviewDetail.tsx
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
  src/utils/apimultipartInstance.tsx
Labels: fix

#237 Feat: 전시글 작성 페이지 관리자만 접근 가능하도록 수정, 유효성 검사 추가
  src/apis/exhbAdmin.tsx
  src/pages/ExhibitionWrite.tsx
  src/utils/exhbTypeSelector.tsx
Labels: enhancement

#248 Fix: 한줄 리뷰 수정기능 http 메서드 수정
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/onelineReview/container/OneLineReadContainer.tsx
  src/components/onelineReview/presentation/OnelineCard.tsx
  src/components/onelineReview/presentation/OnelineWrite.tsx
  src/types/oneLineReview.d.ts
Labels: fix

#264 Fix: 블로그리뷰 상세페이지 버튼들 연결, css 수정
  src/apis/blogReviewApis.tsx
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
  src/components/mate/ExhbCard.tsx
  src/pages/BlogReview.tsx
  src/pages/BlogReviewDetail.tsx
Labels: enhancement

#270 Fix: 블로그리뷰 상세페이지 버튼들 연결, css 수정
  src/apis/blogReviewApis.tsx
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
  src/components/mate/ExhbCard.tsx
  src/pages/BlogReview.tsx
  src/pages/BlogReviewDetail.tsx
Labels: merge main

#255 Fix: 햄버거 메뉴 링크 이동시 닫히도록 수정
  src/components/HamburgerMenu.tsx
  src/components/main/MainArticle.tsx
Labels: enhancement

#256 Fix: 전시 상세정보 항목 추가, 공유하기 기능, 비로그인 북마크 기능 수정
  src/components/atom/BookMark.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
  src/pages/Exhibition.tsx
Labels: enhancement

#276 Fix: 전시 상세정보 항목 추가, 공유하기 기능, 비로그인 북마크 기능 수정
  src/components/atom/BookMark.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
  src/pages/Exhibition.tsx
Labels: merge main

#260 Design: 메이트 작성글 넓이, 블로그/메이트 작성글 공용 Editor 컴포넌트 css 수정
  src/components/Editor.tsx
  src/pages/MateWrite.tsx
Labels: design

#279 Design: 메이트 작성글 넓이, 블로그/메이트 작성글 공용 Editor 컴포넌트 css 수정
  src/components/Editor.tsx
  src/pages/MateWrite.tsx
Labels: merge main

#267 Fix: 토큰만료시에도 로그아웃 버튼 누르면 바로 로그아웃 되도록 수정
  src/apis/logOut.tsx
Labels: bug

#265 Design: 메이트글 목록 max-width 추가
  src/pages/MateList.tsx
Labels: design

#266 Design: 전시회목록 페이지 레이아웃 수정, padding 피그마 추가된 부분 반영
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: design

#282 Design: 전시회목록 페이지 레이아웃 수정, padding 피그마 추가된 부분 반영
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: merge main

#268 Design: 파비콘 변경
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: design

#284 Design: 파비콘 변경
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: merge main

#271 Fix: 메이트 작성/수정 페이지 취소버튼 시 모달 수정, 디자인 수정
  src/pages/MateWrite.tsx
Labels: fix

#272 Fix: 회원가입 시 빈값이면 유효성검사하지 않도록 수정
  src/components/signUp/AdminOnly.tsx
  src/components/signUp/CommonOnly.tsx
  src/components/signUp/EmailAndPw.tsx
Labels: fix

#286 Fix: 회원가입 시 빈값이면 유효성검사하지 않도록 수정
  src/components/signUp/AdminOnly.tsx
  src/components/signUp/CommonOnly.tsx
  src/components/signUp/EmailAndPw.tsx
Labels: merge main

#277 Feat: 메인페이지 재 생성
  package.json
  src/assets/icons/exhibition.svg
  src/assets/icons/mate.svg
  src/assets/icons/review.svg
  src/assets/images/firstSlideImage.jpg
  src/assets/images/thirdSlideImage.jpg
  src/components/Carousel.tsx
  src/components/NewCarousel.tsx
  src/components/main/MainArticle.tsx
  src/pages/Main.tsx
  src/styles/carouselStyle.css
  yarn.lock
Labels: enhancement

#278 Design: header, 햄버거 메뉴 바뀐 디자인 적용
  src/assets/icons/hamburger.svg
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/main/MainArticle.tsx
Labels: design, refactor

#288 Design: header, 햄버거 메뉴 바뀐 디자인 적용
  src/assets/icons/hamburger.svg
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/main/MainArticle.tsx
Labels: merge main

#292 Fix: 메이트글 수정시 기존 선택된 전시회가 나오지 않는 버그, 액세스토큰만료 응답 받아도 로직실행이 안되는 버그 수정
  src/pages/MateWrite.tsx
Labels: bug

#293 Fix: 관리자는 메이트글 작성/수정 할 수 없도록 버튼 숨김, 작성/수정 페이지 접속 시 리다이렉트
  src/components/mate/MateListFilter.tsx
  src/pages/MateWrite.tsx
Labels: fix

#301 Fix: 관리자는 메이트글 작성/수정 할 수 없도록 버튼 숨김, 작성/수정 페이지 접속 시 리다이렉트
  src/components/mate/MateListFilter.tsx
  src/pages/MateWrite.tsx
Labels: merge main

#299 Fix: 블로그 상세페이지 수정
  src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
Labels: enhancement

#297 Feature/simplereviewlist
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/components/mypage/WrittenSimpleReview.tsx
  src/components/onelineReview/container/OneLineReadContainer.tsx
  src/components/onelineReview/presentation/OnelineCard.tsx
  src/components/reviewCommon/ReviewSearchBar.tsx
  src/components/reviewCommon/ReviewWrapper.tsx
Labels: bug, enhancement

#294 전시회 목록 피그마 수정사항 반영, 전시목록 검색창 준비 중입니다 알림창 추가, css 리팩토링
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: fix, design

#305 Refactor: '준비 중인 기능입니다.' alert을 공통적으로 사용할 수 있도록 util함수로 변경, errorAlert함수도 파일 위치 이동
  src/apis/mate.tsx
  src/apis/member.tsx
  src/apis/useRefreshToken.tsx
  src/components/mate/CommentList.tsx
  src/components/mate/MateListFilter.tsx
  src/pages/Login.tsx
  src/pages/MateList.tsx
  src/pages/MateWrite.tsx
  src/utils/alerts.tsx
  src/utils/isApiError.tsx
Labels: merge main

#291 Design: 셀렉트박스 그림자 추가
  src/components/atom/Selectbox.tsx
Labels: design

#307 Design: 셀렉트박스 그림자 추가
  src/components/atom/Selectbox.tsx
Labels: merge main

#296 Fix: 마이페이지 기능 수정
  src/components/HamburgerMenu.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/EditProfile.tsx
  src/pages/Mypage.tsx
Labels: enhancement

#309 Fix: 전시 리뷰 목록 레이아웃과 이미지 없으면 엑박뜨던 부분 수정
  src/App.tsx
  src/components/blogReviewList/ReviewCard.tsx
  src/components/blogReviewList/ReviewCardList.tsx
  src/components/blogreview/container/BlogReviewList.tsx
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/blogreview/presentation/BlogReviewCard.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/pages/BlogReviewList.tsx
Labels: fix

#306 Fix: 전시상세페이지 디자인 수정 북마크 오류 해결
  src/apis/exhibition.tsx
  src/components/atom/BookMark.tsx
  src/components/exhibition/ExhbMateList.tsx
  src/components/exhibition/MainCard.tsx
  src/components/mate/MateCard.tsx
Labels: fix, design

#314 Design: 전시회 상세페이지 상단 전시회 카드부분 디자인 수정
  src/components/mate/CommentList.tsx
  src/components/mate/ExhbCard.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
Labels: design

#311 Design: 전시글 목록/메이트글 목록 - 카드 테두리, 썸네일비율, 썸네일 모양 등 피그마 수정사항 반영
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/mate/MateCard.tsx
Labels: design

#290 Refactor: 임시로 작성했던 myInfoApi에서 내 정보 수정 api 삭제
  src/apis/member.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
Labels: refactor

#319 Design: 반응형 여백 추가, 보더 2px 에서 1px로 변경
  src/components/main/MainArticle.tsx
  src/components/main/NewCarousel.tsx
  src/pages/Main.tsx
Labels: design

#318 Fix: 햄버거메뉴 outside 클릭 영역 수정, Header,Footer 반응형 적용
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
Labels: enhancement, design

#324 Design: 반응형 여백 추가, 보더 2px 에서 1px로 변경
  src/components/Footer.tsx
  src/components/HamburgerMenu.tsx
  src/components/Nav.tsx
  src/components/main/MainArticle.tsx
  src/components/main/NewCarousel.tsx
  src/pages/Main.tsx
Labels: merge main

#327 !HOTFIX: 머지 과정에서 생긴 코드 오류 수정
  src/components/HamburgerMenu.tsx
Labels: bug

#274 Feat: 블로그 디테일 버튼 작업 완료
  src/apis/blogdetailbookMarkApis.tsx
  src/apis/bloglikeApis.tsx
  src/components/blogreview/presentation/BlogReviewDetailPresentation.tsx
Labels: enhancement

#331 Fix: Calendar 컴포넌트 기존 선택된 날짜 보이지 않던 버그 수정, 메이트 모집글 작성/수정페이지 달력 변경사항 반영
  src/components/Calendar.tsx
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
  src/pages/Mate.tsx
  src/pages/MateWrite.tsx
Labels: bug

#332 Fix: Calendar 컴포넌트 기존 선택된 날짜 보이지 않던 버그 수정, 메이트 모집글 작성/수정페이지 달력 변경사항 반영
  src/components/Calendar.tsx
  src/pages/BlogReviewModify.tsx
  src/pages/BlogReviewWrite.tsx
  src/pages/Mate.tsx
  src/pages/MateWrite.tsx
Labels: merge main

#330 Fix: 블로그리뷰 빈칸 작성시 다른 페이지로 이동하는 버그 수정
  src/pages/BlogReviewWrite.tsx
Labels: bug

#329 Feat: 마이페이지 북마크한 블로그리뷰 조회기능 작성
  src/apis/member.tsx
  src/components/blogReviewList/ReviewCardList.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/WrittenBlogReview.tsx
Labels: enhancement

#340 Fix: 전시회 상세페이지에서 블로그리뷰 css 수정(재pr)
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/reviewCommon/ReviewWrapper.tsx
Labels: enhancement

#336 Feat: 마이페이지 좋아요한 블로그리뷰 리스트 조회기능 작성
  src/apis/member.tsx
  src/components/mypage/MenuBtns.tsx
  src/components/mypage/container/LikedBlogReviewContainer.tsx
  src/pages/Mypage.tsx
Labels: enhancement

#350 Fix: 비로그인 상태로 블로그리뷰 상세정보 볼 수 있도록 수정
  src/apis/exhibition.tsx
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/mate/ExhbCard.tsx
  src/types/mate.d.ts
Labels: bug

#351 Fix: 블로그리뷰 상세페이지 프로필 이미지 왜곡 수정
  src/components/onelineReview/presentation/MypageOnelineCard.tsx
  src/components/onelineReview/presentation/OnelineCard.tsx
Labels: bug

#352 Fix/use refresh token
  src/apis/useRefreshToken.tsx
Labels: fix

#356 Fix: 블로그 상세리뷰 페이지 전시 타입 표시 수정
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/onelineReview/presentation/MypageOnelineCard.tsx
  src/pages/BlogReviewDetail.tsx
  src/types/blogReview.d.ts
Labels: enhancement

#353 Design: 전시글 작성 페이지 디자인 수정, 날짜 디폴트 값날짜 수정
  src/components/atom/Selectbox.tsx
  src/pages/ExhibitionWrite.tsx
  src/styles/datePickerStyle.css
Labels: fix, design

#362 Design: 전시글 작성 페이지 디자인 수정, 날짜 디폴트 값날짜 수정
  src/components/atom/Selectbox.tsx
  src/pages/ExhibitionWrite.tsx
  src/styles/datePickerStyle.css
Labels: merge main

#354 Design: 폰트 크기 수정, 햄버거메뉴 기능 수정
  src/components/HamburgerMenu.tsx
Labels: fix, design

#363 Design: 폰트 크기 수정, 햄버거메뉴 기능 수정
  src/components/HamburgerMenu.tsx
Labels: merge main

#337 Design: 검색input 컴포넌트화 후 전시리뷰 목록페이지에 적용
  src/components/atom/SearchInput.tsx
  src/components/blogReviewList/ReviewCard.tsx
  src/components/exhibitionList/Filters.tsx
  src/components/mate/MateListFilter.tsx
  src/pages/BlogReviewList.tsx
Labels: design

#341 Setting: 공통적으로 사용되는 Bg 컬러 추가
  src/components/mate/MateTop.tsx
  src/styles/theme.tsx
Labels: documentation

#365 Setting: 공통적으로 사용되는 Bg 컬러 추가
  src/components/mate/MateTop.tsx
  src/styles/theme.tsx
Labels: merge main

#343 Design: 메인페이지 반응형으로 수정
  src/components/main/MainArticle.tsx
  src/components/main/NewCarousel.tsx
Labels: design

#367 Design: 메인페이지 반응형으로 수정
  src/components/main/MainArticle.tsx
  src/components/main/NewCarousel.tsx
Labels: merge main

#344 Design: footer 반응형으로 수정
  src/components/Footer.tsx
Labels: design

#368 Design: Footer 반응형으로 수정
  src/components/Footer.tsx
Labels: merge main

#369 Design: 메이트글 작성/수정 페이지 놓친 css 수정, 반응형 적용
  src/components/Editor.tsx
  src/pages/MateWrite.tsx
Labels: merge main

#346 메이트글 상세페이지 연결안된 기능, 피그마 수정된 디자인 반영
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/mate/CommentList.tsx
  src/components/mate/ExhbCard.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
  src/types/mate.d.ts
Labels: fix

#370 Fix: 메이트글 상세페이지 연결안된 기능, 피그마 수정된 디자인 반영
  src/components/blogreview/container/BlogReviewDetailContainer.tsx
  src/components/mate/CommentList.tsx
  src/components/mate/ExhbCard.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
  src/types/mate.d.ts
Labels: merge main

#347 Fix: 컴포넌트명 일부 수정, 디자인 수정 - 전시리뷰 상세페이지 상단 전시카드 부분 배경색, 반응형 반영
  src/App.tsx
  src/components/blogReviewList/ReviewCard.tsx
  src/components/blogreview/container/BlogReviewTop.tsx
  src/components/blogreview/presentation/BlogReviewPresentation.tsx
  src/components/mate/ExhbCard.tsx
  src/pages/BlogReview.tsx
Labels: fix

#375 Fix: 전시회 카드 높이 수정, 폰트 크기 변경
  src/components/exhibition/ContentCard.tsx
  src/components/exhibition/MainCard.tsx
Labels: merge main

#376 Feat: 피드백 반영
  src/components/blogreview/presentation/BlogReviewPresentation.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/container/LikedBlogReviewContainer.tsx
  src/components/onelineReview/presentation/OnelineWrite.tsx
  src/components/signUp/CommonOnly.tsx
Labels: enhancement

#359 Fix: 전시회 게시물에서 리뷰가 없는 경우 Nolist 컴포넌트 표시
  src/components/blogreview/container/BlogReviewReadContainer.tsx
  src/components/onelineReview/container/OneLineReadContainer.tsx
  src/pages/BlogReview.tsx
Labels: bug

#374 Fix: 전시글 작성 날짜 포맷팅 수정
  src/pages/ExhibitionWrite.tsx
Labels: fix, design

#380 Fix: 전시글 작성 날짜 포맷팅 수정
  src/pages/ExhibitionWrite.tsx
Labels: merge main

#372 Design: 전시회 목록페이지 피그마 수정사항 반영
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: design

#382 Design: 전시회 목록페이지 피그마 수정사항 반영, 반응형 추가
  src/components/exhibitionList/ExhbCardList.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
Labels: merge main

#373 Design: 메이트글 상세페이지 반응형 추가
  src/components/mate/CommentList.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
Labels: design

#383 Design: 메이트글 상세페이지 반응형 추가
  src/components/mate/CommentList.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
Labels: merge main

#381 Fix: 리프레시 토큰 만료시 로그인 페이지로 리다이렉트
  src/apis/getRefreshToken.tsx
  src/components/HamburgerMenu.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/mypage/WrittenSimpleReview.tsx
  src/components/mypage/container/LikedBlogReviewContainer.tsx
  src/pages/Mypage.tsx
Labels: fix, design

#387 Fix: 리프레시 토큰 만료시 로그인 페이지로 리다이렉트
  src/apis/getRefreshToken.tsx
  src/components/HamburgerMenu.tsx
  src/components/mypage/BookMarkedBlog.tsx
  src/components/mypage/BookMarkedExhb.tsx
  src/components/mypage/BookMarkedMate.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyInfoCard.tsx
  src/components/mypage/WrittenBlogReview.tsx
  src/components/mypage/WrittenMate.tsx
  src/components/mypage/WrittenSimpleReview.tsx
  src/components/mypage/container/LikedBlogReviewContainer.tsx
  src/pages/Mypage.tsx
Labels: merge main

#386 Fix: 메이트 카드 목록의 넓이 비율 수정
  src/components/mate/MateCard.tsx
Labels: fix, design

#391 Fix: 메이트 카드 목록의 넓이 비율 수정
  src/components/mate/MateCard.tsx
Labels: merge main

#388 Fix: 메이트글 상세페이지 전시회카드의 제목길이에 따라 전시회카드 높이 변경되는 로직 추가, 아이콘 추가
  src/assets/icons/calendar.svg
  src/assets/icons/gender.svg
  src/components/mate/ExhbCard.tsx
  src/pages/Mate.tsx
Labels: fix

#395 Fix: 메이트글 상세페이지 전시회카드의 제목길이에 따라 전시회카드 높이 변경되는 로직 추가, 아이콘 추가
  src/assets/icons/calendar.svg
  src/assets/icons/gender.svg
  src/components/mate/ExhbCard.tsx
  src/pages/Mate.tsx
Labels: merge main

#393 Refactor: 전시글 등록 로직 수정
  src/pages/ExhibitionWrite.tsx
Labels: fix, refactor

#397 Refactor: 전시글 등록 로직 수정Dev
  src/pages/ExhibitionWrite.tsx
Labels: merge main

#398 Design: 메이트글 상세페이지 보라색박스 영역 반응형 추가
  src/components/mate/CommentList.tsx
  src/pages/Mate.tsx
Labels: design

#400 Design: 메이트글 상세페이지 보라색박스 영역 반응형 추가
  src/components/mate/CommentList.tsx
  src/pages/Mate.tsx
Labels: merge main

#405 Fix: 전시글 삭제 모달창 추가, 메인카드 이미지 로직 수정
  src/components/exhibition/ContentCard.tsx
  src/components/exhibition/MainCard.tsx
  src/pages/Exhibition.tsx
Labels: fix

#411 Fix: 전시글 삭제 모달창 추가, 메인카드 이미지 로직 수정
  src/components/exhibition/ContentCard.tsx
  src/components/exhibition/MainCard.tsx
  src/pages/Exhibition.tsx
Labels: merge main

#401 Design: 메이트글 상세페이지, 블로그리뷰 상세페이지 전시회 카드영역 반응형 추가
  src/components/mate/ExhbCard.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
Labels: design

#412 @YesunPark Design: 메이트글 상세페이지, 블로그리뷰 상세페이지 전시회 카드영역 반응형 추가
  src/components/mate/ExhbCard.tsx
  src/components/mate/MateTop.tsx
  src/pages/Mate.tsx
Labels: merge main

#408 Feat: silentRefresh
  src/App.tsx
  src/hooks/useSilentRefresh.tsx
  src/pages/Login.tsx
Labels: enhancement

#421 !HOTFIX: 전시회 상세페이지 블로그리뷰 컴포넌트 일부 data가 없을 때의 조건부렌더링 추가해서 에러 해결
  src/components/blogreview/container/BlogReviewReadContainer.tsx
Labels: bug

#423 Fix: 전시회 목록 정렬 필터 인기순-> 조회수순으로 변경, 기능 추가 + api 수정됨
  src/apis/getExhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
  src/types/exhbList.d.ts
Labels: fix

#424 Fix: 전시회 목록 정렬 필터 인기순-> 조회수순으로 변경, 기능 추가 + api 수정됨
  src/apis/getExhbList.tsx
  src/components/ExhibitionChoice.tsx
  src/components/exhibitionList/Filters.tsx
  src/pages/ExhibitionList.tsx
  src/types/exhbList.d.ts
Labels: merge main

#425 Fix: 메이트글 목록 조회 api 수정, 메이트글 목록 조회 실패시 메인페이지로 리다이렉트 기능 추가
  src/apis/mate.tsx
  src/pages/MateList.tsx
Labels: bug, fix

#431 Fix: 메이트글 목록 조회 api 수정, 메이트글 목록 조회 실패시 메인페이지로 리다이렉트 기능 추가
  src/apis/mate.tsx
  src/pages/MateList.tsx
Labels: merge main

#429 Fix: 전시회목록 필터 종류 추가
  src/components/exhibitionList/Filters.tsx
  src/types/exhbList.d.ts
Labels: fix

#430 Feat: 관람료 "미정" 추가
  src/components/exhibition/MainCard.tsx
  src/pages/ExhibitionWrite.tsx
Labels: fix

#438 Feat: 관람료 "미정" 추가
  src/components/exhibition/MainCard.tsx
  src/pages/ExhibitionWrite.tsx
Labels: merge main

#436 Design: 파비콘 간헐적으로 리액트아이콘으로 뜨는 오류 수정
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: bug, design

#439 Design: 파비콘 간헐적으로 리액트아이콘으로 뜨는 오류 수정
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: merge main

#437 Delete: 로그인페이지 이메일/비밀번호 찾기 기능 삭제
  src/pages/Login.tsx
Labels: fix

#440 Delete: 로그인페이지 이메일/비밀번호 찾기 기능 삭제
  src/pages/Login.tsx
Labels: merge main

#426 Fix: 변경된 api 주소로 변경
  src/apis/blogdetailbookMarkApis.tsx
  src/apis/bloglikeApis.tsx
  src/apis/exhibition.tsx
  src/apis/member.tsx
  src/components/blogreview/presentation/BlogReviewPresentation.tsx
Labels: refactor

#444 Design: 전시리뷰 목록 없을 시 NoList 컴포넌트 레이아웃 깨짐 수정
  src/components/blogReviewList/ReviewCardList.tsx
Labels: design

#445 Design: 전시리뷰 목록 없을 시 NoList 컴포넌트 레이아웃 깨짐 수정
  src/components/blogReviewList/ReviewCardList.tsx
Labels: merge main

#441 Fix: 전시글 등록시 관람료 무료 / 미정 버튼 라디오 형식으로 수정
  src/pages/ExhibitionWrite.tsx
Labels: fix

#447 Fix: 전시글 등록시 관람료 무료 / 미정 버튼 라디오 형식으로 수정
  src/pages/ExhibitionWrite.tsx
Labels: merge main
